
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    # Matrix: roda em Linux, macOS e Windows, usando Node 18.x
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x]

    # Define que todos os comandos serão executados dentro de ./api
    defaults:
      run:
        working-directory: ./api

    steps:
      # 1) Faz checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Configura Node.js na versão da matrix
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # 3) Instala as dependências do back-end
      - name: Install dependencies
        run: npm ci

      # 4) Gera o Prisma Client
      - name: Generate Prisma client
        run: npx prisma generate

      # 5) Roda os testes unitários com coverage
      - name: Run tests with coverage
        env:
          APP_URL: http://localhost:3000
          PORT: 3030
          DATABASE_URL: mysql://root:pwd@localhost:3306/cuthub
          SECRET_KEY: cu7Hu3
          JWT_EXPIRATION: 3d
          AWS_ACCESS_KEY_ID: valor
          AWS_SECRET_ACCESS_KEY: Valor
          AWS_BUCKET_REGION: sa-east-1
          AWS_BUCKET: geoprospect 
          AWS_BUCKET_NAME: geoprospect
          EMAIL_ACCOUNT: teste1@gmail.com
          EMAIL_PASSWORD: 123
          NODE_ENV: test
        run: npm test -- --coverage

